version: "3.8"

services:
  flaskapp:
    build: .
    container_name: flaskapp
    ports:
      - "8000:8000"

    environment:
      MYSQL_HOST: flask-mariadb-db.cnwcmsquw4d7.ap-south-2.rds.amazonaws.com
      MYSQL_USER: flaskdb
      MYSQL_PASSWORD: Tsanjay212
      MYSQL_DB: sanreach
      REDIS_HOST: 172.16.0.2
      REDIS_PASSWORD: Tsanjay212

    restart: always